services:
  postgres:
    image: postgis/postgis:10-2.5-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "psql postgresql://postgres@:5432/postgres -c 'select 1;'" ]
      interval: 10s
      timeout: 5s
      retries: 20
    command: ["postgres", "-c", "log_statement=all"]

  liquibase-people_activity:
    build: .
    container_name: liquibase-users
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "sleep 5 && /create-db-user.sh && tail -f /dev/null
      && liquibase \
        --logLevel=INFO
        --driver=org.postgresql.Driver
        --url="jdbc:postgresql://postgres:5432/postgres"
        --username=postgres
        --password=postgres
      update"
#    volumes:
#      - ./changelog:/liquibase/changelog