services:
  postgres:
    image: postgis/postgis:10-2.5-alpine
    volumes:
      - type: bind
        source: ./create_db.sh
        target: /docker-entrypoint-initdb.d/create_db.sh
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "psql postgresql://postgres@:5432/ku_users -c 'select 1;'" ]
      interval: 10s
      timeout: 3s
      retries: 15

  liquibase-users:
    image: liquibase/liquibase:4.17.2
    container_name: liquibase-users
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./databases/:/databases/
    command: >
      liquibase
        --logLevel=INFO
        --driver=org.postgresql.Driver
        --classpath="/databases/ku-users/"
        --changeLogFile="changelog.xml"
        --url="jdbc:postgresql://postgres:5432/ku_users"
        --username=ku_users_app
        --password=password  
      update

  liquibase-devices:
    image: liquibase/liquibase:4.17.2
    container_name: liquibase-devices
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./databases/:/databases/
    command: >
      liquibase
        --logLevel=INFO
        --driver=org.postgresql.Driver
        --classpath="/databases/ku-devices/"
        --changeLogFile="changelog.xml"
        --url="jdbc:postgresql://postgres:5432/ku_devices"
        --username=ku_devices_app
        --password=password
        --contexts="data_migration"
      update

  zookeeper:
    image: zookeeper:3.7.0
    container_name: zookeeper
    restart: "no"
    ports:
      - "2181:2181"

  kafka:
    image: obsidiandynamics/kafka
    container_name: kafka
    restart: "no"
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DOCKER_INTERNAL:PLAINTEXT,DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: DOCKER_INTERNAL://:29092,DOCKER_EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: DOCKER_INTERNAL://kafka:29092,DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PORT=6379
      - REDIS_DATABASES=16