server:
  port: 8082

ku-gateway:
  users-url: http://localhost:8080/users

spring:
  security:
    jwt:
      issuer: anastasia.yurkova2003@gmail.com
      expiration: 2d
  kafka:
    bootstrap-servers:
      localhost: 9092

topic:
  pings:
    name: ping
  coordinates:
    name: coordinates

auto:
  create:
    topics:
      enable: true