server:
  port: 8081

spring:
  kafka:
    consumer:
      group-id: "device"
      max-poll-records: 100
      properties:
        auto.create.topics.enable: true
  datasource:
    url: jdbc:postgresql://localhost:5432/ku_devices
    driver-class-name: org.postgresql.Driver
    username: ku_devices_app
    password: password

topic:
  pings:
    name: ping