server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ku_users
    driver-class-name: org.postgresql.Driver
    username: ku_users_app
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show_sql: true
    format_sql: true